# Generated by Django 4.1 on 2022-10-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0006_cartas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cartas'),
        ),
    ]
