# Generated by Django 4.1 on 2022-10-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0007_alter_cartas_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comprador',
        ),
        migrations.DeleteModel(
            name='vendedor',
        ),
    ]
