# Generated by Django 4.1 on 2022-10-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0008_delete_comprador_delete_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='artista',
            field=models.CharField(default='unknown', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartas',
            name='descripcion',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
