# Generated by Django 4.1 on 2022-10-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0009_cartas_artista_cartas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartas',
            name='rareza',
            field=models.CharField(default='common', max_length=10),
            preserve_default=False,
        ),
    ]
