# Generated by Django 4.1 on 2022-10-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0010_cartas_rareza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas',
            name='rareza',
            field=models.CharField(max_length=13),
        ),
    ]
